title: PrevCons aszaló
database_name: PrevCons.sqlite3
excluded_tables: {'prevcons'}
excluded_columns: {'clause'}
displayed_column_table_name: prevcons
displayed_column_name: clause
default:
    # friendly_name
    table_name: prevcons
    fn_value: ''
    fn_not: false
    fn_regex: false
    # api_name
    value: ''
    not: false
    regex: false
    sort_key: false
    featelems_aliases: {}
    limit: 40
    radio_tooltip: Találatok listázása az alábbi szempont szerint
    # field_name_tooltip: A mező rövid leírása
    not_tooltip: Negatív szűrés
    regex_tooltip: Reguláris kifejezések engedélyezése
    featname_not_tooltip: Negatív szűrés
    featname_regex_tooltip: Reguláris kifejezések engedélyezése

fields:
    - friendly_name: igekötő
      col_name: prev
      api_name: prev
      sort_key: true
      field_name_tooltip: A keresendő igekötő(k)

    - friendly_name: igelemma
      col_name: verb
      api_name: verb
      field_name_tooltip: A keresendő igelemma(ák)

    - friendly_name: szóalak
      col_name: actform
      api_name: actform
      field_name_tooltip: A keresendő igealak(ok)

    - friendly_name: vonzatkeret
      col_name: argframe
      api_name: argframe
      field_name_tooltip: A keresendő vonzatkeret

    - friendly_name: igekötő produktivitása
      col_name: prev_prod
      api_name: prev_prod
      field_name_tooltip: Az igekötő produktivitása

    - friendly_name: igekötő hapaxai (db)
      col_name: prev_hapaxes
      api_name: prev_hapaxes
      field_name_tooltip: Az igekötő hapaxai (db)

    - friendly_name: igealkotási mód
      col_name: inputtype
      api_name: inputtype
      field_name_tooltip: Az igealkotási mód

    - friendly_name: a képző/h.séma típusa
      col_name: suffixtype
      api_name: suffixtype
      field_name_tooltip: A képző/h.séma típusa

    - friendly_name: CV-séma
      col_name: phonotype
      api_name: phonotype
      field_name_tooltip: A hangzásséma (C = mássalhangzó, V = magánhangzó)

    - friendly_name: stílusregiszter
      col_name: style
      api_name: style
      field_name_tooltip: A stílusregiszter(ek)

    - friendly_name: régió
      col_name: region
      api_name: region
      field_name_tooltip: A régió(k)

    - friendly_name: word2vec bemenet
      col_name: w2v_input
      api_name: w2v_input
      field_name_tooltip: A word2vec bemenet

    - friendly_name: word2vec klaszter
      col_name: w2v_cluster
      api_name: w2v_cluster
      field_name_tooltip: A word2vec klaszter

    - friendly_name: tagmondat
      col_name: clause
      api_name: clause
      regex: true
      field_name_tooltip: A tagmondat (kikapcsolt Regex opcióval teljes tagmondatra történő egyezést néz)

    - friendly_name: teljes mondat
      col_name: sent
      api_name: sent
      regex: true
      field_name_tooltip: A teljes mondat (kikapcsolt Regex opcióval teljes mondatra történő egyezést néz)

ui-strings:
    locale: hu_HU.UTF-8
    submit: Küldés
    reset: Visszaállítás (a legutolsó paraméterekre)
    clear_field_values: Minden érték törlése
    n_more_elems: "{0} további találat nem került megjelenítésre"
    save_as_tsv: Eredmények mentése TSV formátumban
    save_as_json: Eredmények mentése JSON formátumban
    regex_disabled: A regex le van tiltva a {0} ({1}) mezőnél, mert nem sting típus, de a regex checkbox (paraméter) be van pipálva!
    sort_key_invalid: A rendezési kulcs (sort) üres vagy érvénytelen az értéke, vagy a rendezési kulcsnak választott mező értéke érvénytelen!
    featname_in_multiple_fields: A feat név ({0}) használata több mezőben ({1}) nem megengedett!
    same_feature_with_pos_and_neg_signs: Ugyanazon jellemző ({0}) pozitív és negatív előjellel történő használata több mezőben ({1}) nem megengedett!
    too_mutch_features_specified: Egy lekérdezésben csak 60 jellemző megengedett {0} helyett !
    featname_value_too_broad_regex: A \'{1}\' ({2}FEATNAME) mezőben jellemzőnév értéke ({0}) túl tág reguláris kifejezés !
    invalid_format: A FORMAT paraméter értéke ({0}) érvénytelen (lehetséges értékek:\ {1} ) !
    invalid_value: A \'{1}\' ({2}) mező értéke ({0}) nincs az elérhető elemek között!
    featname_invalid_value: A \'{1}\' ({2}FEATNAME) mező jellemzőnevének értéke ({0}) nem szerepel az elérhető elemek között!
    invalid_regex: A \'{1}\' ({2}) mezőben megadott érték ({0}) érvénytelen reguláris kifejezés!
    featname_invalid_regex: A \'{1}\' ({2}FEATNAME) mezőben megadott jellemzőnév értéke ({0}) érvénytelen reguláris kifejezés !
    non_empty_value_for_empty_featname: A \'{1}\' ({2}) mezőben megadott érték nem lehet üres ({0}) üres jellemzőnév mellett!
    featname_regex_invalid_value: A \'{1}\' ({2}FEATNAME) mezőben megadott jellemzőnév értéke ({0}) reguláris kifejezés, de nem illeszkedik egy elérhető értékre sem!
    footer: Adatbázis:\ Kalivoda Ágnes – <a href="https://github.com/kagnes/prevcons">PrevCons</a><br>
            Webes keresőfelület:\ Indig Balázs – <a href="https://github.com/dlazesz/aszalo">Aszaló</a><br>
            Mintául szolgált:\ Sass Bálint – <a href="http://corpus.nytud.hu/mazsola/">Mazsola</a><br>
            <br><br>
            Példa:\ <a onclick="clearAllValues();setValuesForField('prev', 'be');setValuesForField('argframe', '-t');setValuesForField('style', '', true);" href="javascript:void(0);">"A be... -t stílusregiszter szerint rendezve"</a>
            <br><br>
            Hibajelentés:\ <a href="https://bit.ly/aszalohibajelento">https://bit.ly/aszalohibajelento</a><br>
            <br>
            <p>A PrevCons felhasználása esetén az alábbi publikációk egyike hivatkozandó:</p>
            <ul>
                <li><a href="https://doi.org/10.34103/ARGUMENTUM/2021/4">Kalivoda Ágnes (2021). Az igekötők produktív kapcsolódási mintái. Argumentum 17. p. 56-82. https://doi.org/10.34103/ARGUMENTUM/2021/4</a></li>
                <li><a href="https://github.com/kagnes/phd_thesis">Kalivoda Ágnes (2021). Igekötős szerkezetek a magyarban. Doktori értekezés. PPKE BTK, Nyelvtudományi Doktori Iskola. Budapest. Megjelenés alatt.</a></li>
            </ul>
